## Can Automated Regression beat linear model?

*Authors: Bartłomiej Granat, Szymon Maksymiuk, (Warsaw University of Technology)*

### Abstract


### Introduction and Motivation

### Data

### Methodology

AutoMl Model $M_{aml}$ and the dataset $D$ that consists of $D_{X} = X$ which is set of independent variables and $D_{y} = y$ - dependent variable (ie. target). We assume that $M_{aml}$ is an unknown function $M_{aml}: \mathbb{R}^{p} \to \mathbb{R}$, where p is a snumber of features in the $D$ Dataset, that satisfies $y = M_{aml}(X) + \epsilon$ where $\epsilon$ is an error vector. Automated regression constructs known vector function $G_{AR} : \mathbb{R}^{n \times p} \to \mathbb{R}^{n \times p}$ where $n$ is a number of observations, that satisfies $y = G_{AR}(X)\beta + \epsilon$ thus it is linear regression model fitted for transformated data.

To find $G_{AR}$ we have to put some constraints. First of all we want it to minimize loss function $L: \mathbb{R}^{n} \to \mathbb{R}$ given by following formula $L : \frac{\sum_{i=1}^{n}(y_{i}-\hat{y_{i}})^{2}\sum_{i=1}^{n}(y_{i}-\bar{y_{i}})^{2}}{\sum_{i=1}^{n}(\hat{y_{i}}-\bar{y_{i}})^{2}}$ which can be interpreted as Mean Square Error divided by the R-squred coefficient of determination and stands as a tradeoff between fit and results. Another constraint is a domain of valid transformations of particular variables. For given dataset, described in the previous paragraphs we decided to use:
* Feature selection
  + XAI feature Importance
  + AIC/BIC
* Continuous transformation
  + Polynomial transformation 
  + Lograthmic transformation
* Discrete transformation
  + SAFE method
* Feature concatenation
  + Multiplication of pair of features.


Obviously, XAI related methods are conducted using AutoML Model. We've decided to omit data imputation as an element of valid transformations dataset because liver-disorders dataset does not meet with the problem of missing values. 

The optimization process is conducted based on Bayesian Optimization and the backtracing idea. Each main element of the domain of valid transformations is one step in the process of creation $G_{AR}$ function. Within each step, Bayesian optimization will be used to find the best transformation for the given level. During further steps, if any of transformation did not improve model, ie. $L$ function was only growing, the algorithm takes second, the third, etc. solution from previous steps according to backtracking idea. If for no one of $k$ such iterations, where k is known parameter, a better solution is found, step is omitted. 

### Results


### Summary and conclusions 

